//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_CHA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU_CHA()
        {
            this.DS_QUYEN_MENU = new HashSet<DS_QUYEN_MENU>();
            this.MENU_CON = new HashSet<MENU_CON>();
        }
    
        public int ID_MENU_CHA { get; set; }
        public string TEN_MENU_CHA { get; set; }
        public string LINK { get; set; }
        public string ICON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_QUYEN_MENU> DS_QUYEN_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_CON> MENU_CON { get; set; }
    }
}
