//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHULUC
    {
        public int ID_PHULUC { get; set; }
        public int HOPDONG_ID { get; set; }
        public string SOHD_PHULUC { get; set; }
        public Nullable<System.DateTime> NGAYHD_PHULUC { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual HOPDONG_CHIPHI HOPDONG_CHIPHI { get; set; }
    }
}
