//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG_NHANCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOPDONG_NHANCONG()
        {
            this.THANHTOAN_NHANCONG = new HashSet<THANHTOAN_NHANCONG>();
        }
    
        public int HOPDONG_NHANCONG_ID { get; set; }
        public Nullable<int> HTTT_ID { get; set; }
        public Nullable<int> CHUKY_ID { get; set; }
        public Nullable<int> NAM_HD_ID { get; set; }
        public Nullable<int> ID_LOAIHD_SUB { get; set; }
        public Nullable<int> THOIHAN_TT_ID { get; set; }
        public string SO_HD { get; set; }
        public Nullable<System.DateTime> NGAY_HD { get; set; }
        public string TEN_BT { get; set; }
        public string DIACHI_BT { get; set; }
        public string DIENTHOAI_BT { get; set; }
        public string FAX_BT { get; set; }
        public string TAIKHOAN_BT { get; set; }
        public string NGANHANG_BT { get; set; }
        public string MSTHUE_BT { get; set; }
        public string DAIDIEN_BT { get; set; }
        public string CMND_BT { get; set; }
        public Nullable<System.DateTime> NGAYCAP_CMND_BT { get; set; }
        public string NOICAP_BT { get; set; }
        public string CHUCVU_BT { get; set; }
        public string TEN_CT { get; set; }
        public string DIACHI_CT { get; set; }
        public string CMND_CT { get; set; }
        public Nullable<System.DateTime> NGAYCAP_CT { get; set; }
        public string NOICAP_CT { get; set; }
        public Nullable<System.DateTime> NGAYSINH_CT { get; set; }
        public string DIENTHOAI_CT { get; set; }
        public string TRINHDO_CT { get; set; }
        public string MSTHUE_CT { get; set; }
        public string CONGVIEC_CT { get; set; }
        public string NOIO_CT { get; set; }
        public string NOILAMVIEC_CT { get; set; }
        public Nullable<decimal> THANG_GT { get; set; }
        public Nullable<decimal> TONG_GT { get; set; }
        public Nullable<System.DateTime> NGAY_BD { get; set; }
        public Nullable<System.DateTime> NGAY_KT { get; set; }
        public string GHICHU { get; set; }
        public string FIle { get; set; }
        public string USER { get; set; }
        public Nullable<int> DONVI_ID { get; set; }
        public Nullable<decimal> THANG { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<int> SO_CHUKY { get; set; }
        public Nullable<decimal> SLTRAM_KYTHUAT { get; set; }
        public string TENTRAM_KYTHUAT { get; set; }
        public Nullable<decimal> LUONG_KYTHUAT { get; set; }
        public Nullable<decimal> SLTRAM_TAISAN { get; set; }
        public string TENTRAM_TAISAN { get; set; }
        public Nullable<decimal> LUONG_TAISAN { get; set; }
        public Nullable<decimal> SLTRAM_MPD { get; set; }
        public string TENTRAM_MPD { get; set; }
        public Nullable<decimal> LUONG_MPD { get; set; }
        public Nullable<decimal> SLTRAM_BAOVE { get; set; }
        public string TENTRAM_BAOVE { get; set; }
        public Nullable<decimal> LUONG_BAOVE { get; set; }
        public Nullable<decimal> THULAO { get; set; }
        public Nullable<decimal> SOTIEN_BAOHIEM { get; set; }
        public Nullable<decimal> SO_SOBAOHIEM { get; set; }
        public Nullable<int> VTT_KHONGHOTRO { get; set; }
        public Nullable<int> ID_TRANGTHAI { get; set; }
    
        public virtual CHUKY_TT CHUKY_TT { get; set; }
        public virtual DONVI DONVI { get; set; }
        public virtual TRANGTHAI_HD TRANGTHAI_HD { get; set; }
        public virtual NAM_HD NAM_HD { get; set; }
        public virtual THOIHAN_TT THOIHAN_TT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOAN_NHANCONG> THANHTOAN_NHANCONG { get; set; }
        public virtual HTTT HTTT { get; set; }
        public virtual LOAI_HD_SUB LOAI_HD_SUB { get; set; }
    }
}
