//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUTHE_HOPDONG
    {
        public int CHUTHE_HOPDONG_ID { get; set; }
        public string TEN_CHUTHE { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string DAIDIEN { get; set; }
        public string CHUCVU { get; set; }
        public string STK_NGANHANG { get; set; }
        public string TEN_NGANHANG { get; set; }
        public string MSTHUE { get; set; }
        public string GHICHU { get; set; }
    }
}
