//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LOAI_HOPDONG
    {
        public int LOAI_HOPDONG_ID { get; set; }
        public int HOPDONG_DT_CNTT_ID { get; set; }
        public string TEN_LOAI_HOPDONG { get; set; }
        public string GHICHU { get; set; }
    }
}
