//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_CNTT_TIENDO_TT
    {
        public int TIENDO_TT_ID { get; set; }
        public int HOPDONG_DT_CNTT_ID { get; set; }
        public int DOT_TT { get; set; }
        public Nullable<decimal> GIATRI_TT { get; set; }
        public Nullable<decimal> THOIGIAN_TT { get; set; }
        public Nullable<System.DateTime> THOIHAN_TT { get; set; }
        public string SO_HOADON { get; set; }
        public string NGAY_HOADON { get; set; }
        public Nullable<int> TRANGTHAI_XUAT_HOADON { get; set; }
        public Nullable<int> TRANGTHAI_TT { get; set; }
        public string FILE { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> FILE_ID { get; set; }
    
        public virtual HOPDONG_DT_CNTT HOPDONG_DT_CNTT { get; set; }
    }
}
