//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG_DT_CNTT
    {
        public int HOPDONG_DT_CNTT_ID { get; set; }
        public string SO_HOPDONG { get; set; }
        public string TEN_HOPDONG { get; set; }
        public string TEN_GOITHAU { get; set; }
        public string TEN_DUAN { get; set; }
        public int LOAI_HOPDONG_ID { get; set; }
        public Nullable<int> CHUKY_ID { get; set; }
        public Nullable<int> HTTT_ID { get; set; }
        public Nullable<int> NAM_HD_ID { get; set; }
        public Nullable<int> THOIHAN_TT_ID { get; set; }
        public string SO_HD { get; set; }
        public Nullable<System.DateTime> NGAY_HD { get; set; }
        public int BEN_THUE_ID { get; set; }
        public int BEN_CHOTHUE_ID { get; set; }
        public Nullable<decimal> GIATRI_PHANCUNG_HD { get; set; }
        public Nullable<decimal> GIATRI_DICHVU_HD { get; set; }
        public Nullable<decimal> GIATRI_TAMUNG { get; set; }
        public Nullable<System.DateTime> NGAY_HIEULUC_HD { get; set; }
        public Nullable<System.DateTime> NGAY_BBNT { get; set; }
        public Nullable<decimal> GIATRI_BLTHHD { get; set; }
        public Nullable<System.DateTime> NGAY_BLTHHĐ { get; set; }
        public Nullable<decimal> THOIGIAN_BLTHHD { get; set; }
        public Nullable<System.DateTime> NGAY_HETHAN_BLTHHĐ { get; set; }
        public string GHICHU { get; set; }
        public string FILE { get; set; }
        public string USER { get; set; }
        public Nullable<int> DONVI_ID { get; set; }
        public Nullable<decimal> THANG { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<int> SO_CHUKY { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
    
        public virtual CHUKY_TT CHUKY_TT { get; set; }
        public virtual CHUKY_TT CHUKY_TT1 { get; set; }
        public virtual DONVI DONVI { get; set; }
        public virtual DONVI DONVI1 { get; set; }
        public virtual HTTT HTTT { get; set; }
        public virtual HTTT HTTT1 { get; set; }
        public virtual NAM_HD NAM_HD { get; set; }
        public virtual NAM_HD NAM_HD1 { get; set; }
        public virtual THOIHAN_TT THOIHAN_TT { get; set; }
        public virtual THOIHAN_TT THOIHAN_TT1 { get; set; }
    }
}
