//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSU_DANGNHAP
    {
        public int LICHSU_ID { get; set; }
        public string TENTRUYCAP { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TRANGTHAI { get; set; }
    }
}
