//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHD2Entities : DbContext
    {
        public QLHD2Entities()
            : base("name=QLHD2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENTHUE_TAM> BENTHUE_TAM { get; set; }
        public virtual DbSet<CHUKY_TT> CHUKY_TT { get; set; }
        public virtual DbSet<DM_CHUTHE_HOPDONG> DM_CHUTHE_HOPDONG { get; set; }
        public virtual DbSet<DM_LOAI_HOPDONG> DM_LOAI_HOPDONG { get; set; }
        public virtual DbSet<DM_VANBAN> DM_VANBAN { get; set; }
        public virtual DbSet<DONVI> DONVIs { get; set; }
        public virtual DbSet<DS_QUYEN_MENU> DS_QUYEN_MENU { get; set; }
        public virtual DbSet<DT_CNTT_TIENDO_TT> DT_CNTT_TIENDO_TT { get; set; }
        public virtual DbSet<HETHONG> HETHONGs { get; set; }
        public virtual DbSet<HISTORY_CHANGE> HISTORY_CHANGE { get; set; }
        public virtual DbSet<HOPDONG_CHIPHI> HOPDONG_CHIPHI { get; set; }
        public virtual DbSet<HOPDONG_DOANHTHU> HOPDONG_DOANHTHU { get; set; }
        public virtual DbSet<HOPDONG_DT_CNTT> HOPDONG_DT_CNTT { get; set; }
        public virtual DbSet<HOPDONG_NHANCONG> HOPDONG_NHANCONG { get; set; }
        public virtual DbSet<HTTT> HTTTs { get; set; }
        public virtual DbSet<LICHSU_DANGNHAP> LICHSU_DANGNHAP { get; set; }
        public virtual DbSet<LOAI_HD_SUB> LOAI_HD_SUB { get; set; }
        public virtual DbSet<MENU_CHA> MENU_CHA { get; set; }
        public virtual DbSet<MENU_CON> MENU_CON { get; set; }
        public virtual DbSet<NAM_HD> NAM_HD { get; set; }
        public virtual DbSet<PHULUC> PHULUCs { get; set; }
        public virtual DbSet<PHULUC_HDCP> PHULUC_HDCP { get; set; }
        public virtual DbSet<PL_HD_DOANHTHU_CNTT> PL_HD_DOANHTHU_CNTT { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_FILE> TBL_FILE { get; set; }
        public virtual DbSet<THANHLY_HDCHIPHI> THANHLY_HDCHIPHI { get; set; }
        public virtual DbSet<THANHLY_HDDOANHTHU> THANHLY_HDDOANHTHU { get; set; }
        public virtual DbSet<THANHLY_HDNHANCONG> THANHLY_HDNHANCONG { get; set; }
        public virtual DbSet<THANHTOAN_CHIPHI> THANHTOAN_CHIPHI { get; set; }
        public virtual DbSet<THANHTOAN_DOANHTHU> THANHTOAN_DOANHTHU { get; set; }
        public virtual DbSet<THANHTOAN_NHANCONG> THANHTOAN_NHANCONG { get; set; }
        public virtual DbSet<THANHVIEN> THANHVIENs { get; set; }
        public virtual DbSet<THOIHAN_TT> THOIHAN_TT { get; set; }
        public virtual DbSet<TINHTRANG_SD_CHIPHI> TINHTRANG_SD_CHIPHI { get; set; }
        public virtual DbSet<TRAM_BTS> TRAM_BTS { get; set; }
        public virtual DbSet<TRANGTHAI_HD> TRANGTHAI_HD { get; set; }
    }
}
