//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHULUC_HDCP
    {
        public int PHULUC_HDCP_ID { get; set; }
        public Nullable<int> HOPDONG_CHIPHI_ID { get; set; }
        public Nullable<int> CHUKY_ID { get; set; }
        public Nullable<int> CHUKY2_ID { get; set; }
        public string SO_PHULUC { get; set; }
        public string TEN_CT { get; set; }
        public Nullable<System.DateTime> NGAY_KY_PL { get; set; }
        public Nullable<System.DateTime> NGAY_BD_PL { get; set; }
        public Nullable<System.DateTime> NGAY_KT_PL { get; set; }
        public Nullable<decimal> THANG_GT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> TONG_GT { get; set; }
        public Nullable<int> SOCHUKY { get; set; }
        public string GHICHU { get; set; }
        public Nullable<decimal> THANG { get; set; }
        public string FILE { get; set; }
        public Nullable<System.DateTime> NGAY_HIEU_LUC_PL { get; set; }
        public Nullable<int> FILE_ID { get; set; }
    
        public virtual CHUKY_TT CHUKY_TT { get; set; }
        public virtual CHUKY_TT CHUKY_TT1 { get; set; }
        public virtual HOPDONG_CHIPHI HOPDONG_CHIPHI { get; set; }
    }
}
