//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_HD_DOANHTHU_CNTT
    {
        public int PHULUC_HDCNTT_ID { get; set; }
        public int HOPDONG_DT_CNTT_ID { get; set; }
        public string SO_PHULUC { get; set; }
        public Nullable<System.DateTime> NGAY_KY_PL { get; set; }
        public int BEN_THUE_ID { get; set; }
        public int BEN_CHOTHUE_ID { get; set; }
        public Nullable<decimal> GIATRI_PHANCUNG_HD { get; set; }
        public Nullable<decimal> GIATRI_DICHVU_HD { get; set; }
        public Nullable<System.DateTime> NGAY_HIEULUC_HD { get; set; }
        public Nullable<System.DateTime> NGAY_BBNT { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string file { get; set; }
        public Nullable<System.DateTime> NGAY_HIEU_LUC_PL { get; set; }
        public Nullable<int> FILE_ID { get; set; }
    
        public virtual DM_CHUTHE_HOPDONG DM_CHUTHE_HOPDONG { get; set; }
        public virtual DM_CHUTHE_HOPDONG DM_CHUTHE_HOPDONG1 { get; set; }
        public virtual HOPDONG_DT_CNTT HOPDONG_DT_CNTT { get; set; }
    }
}
