//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLDA_CNTT_TIENDO
    {
        public int TIENDO_DA_ID { get; set; }
        public int DUAN_ID { get; set; }
        public string TEN_TIENDO_DA { get; set; }
        public int DONVI_CHUTRI { get; set; }
        public int NGUOI_THUCHIEN { get; set; }
        public Nullable<int> TRANGTHAI_THUCHIEN { get; set; }
        public Nullable<System.DateTime> NGAY_GIAO { get; set; }
        public Nullable<System.DateTime> NGAY_HETHAN { get; set; }
        public Nullable<int> FILE_ID { get; set; }
        public string GHICHU_HIENTRANG { get; set; }
        public string GHICHU_TONDONG { get; set; }
        public decimal STT { get; set; }
        public Nullable<bool> VTT { get; set; }
    
        public virtual DONVI DONVI { get; set; }
        public virtual QLDA_CNTT QLDA_CNTT { get; set; }
        public virtual TBL_FILE TBL_FILE { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
