//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FILE
    {
        public int file_id { get; set; }
        public string file_name { get; set; }
        public string file_ext { get; set; }
        public string file_base6 { get; set; }
    }
}
