//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHLY_HDNHANCONG
    {
        public int THANHLY_HDNHANCONG1 { get; set; }
        public int HOPDONG_NHANCONG_ID { get; set; }
        public Nullable<decimal> SOBIENBAN_TL { get; set; }
        public Nullable<System.DateTime> NGAYLAP_BBTL { get; set; }
        public string TEN_CTV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<decimal> CMND { get; set; }
        public Nullable<System.DateTime> NGAY_HIEULUC_TL { get; set; }
        public string GHICHU { get; set; }
    }
}
