//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANHVIEN()
        {
            this.DS_QUYEN_MENU = new HashSet<DS_QUYEN_MENU>();
        }
    
        public int ID_THANHVIEN { get; set; }
        public Nullable<decimal> HETHONG_ID { get; set; }
        public string TEN_THANHVIEN { get; set; }
        public string CHUCVU { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public string TRINHDO { get; set; }
        public string TONGIAO { get; set; }
        public string DANTOC { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string CMND { get; set; }
        public string NOICAP { get; set; }
        public Nullable<System.DateTime> NGAYCAP { get; set; }
        public string TENTRUYCAP { get; set; }
        public string MATKHAU { get; set; }
        public string IMG { get; set; }
        public Nullable<int> DONVI_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_QUYEN_MENU> DS_QUYEN_MENU { get; set; }
        public virtual HETHONG HETHONG { get; set; }
    }
}
