//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public int ID_TT { get; set; }
        public int HOPDONG_ID { get; set; }
        public Nullable<System.DateTime> NGAY_TT { get; set; }
        public Nullable<decimal> SOTIEN_TT { get; set; }
        public string GHICHU_TT { get; set; }
    
        public virtual HOPDONG_CHIPHI HOPDONG_CHIPHI { get; set; }
    }
}
