//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENTRINH
    {
        public int TIENTRINH_ID { get; set; }
        public int HOPDONG_ID { get; set; }
        public string TEN_TIENTRINH { get; set; }
        public string NGUOIPHUTRACH { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public Nullable<System.DateTime> DEADLINE { get; set; }
        public string FILE { get; set; }
        public Nullable<bool> IsVTT { get; set; }
        public Nullable<int> TIENDO_ID { get; set; }
    
        public virtual TIENDO TIENDO { get; set; }
    }
}
