//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAM_BTS
    {
        public string MA_TRAM { get; set; }
        public string TEN_TRAM { get; set; }
        public string DIA_CHI_TRAM { get; set; }
        public string LONG_TRAM { get; set; }
        public string LAT_TRAM { get; set; }
        public int TRAM_ID { get; set; }
        public int TRANG_THAI { get; set; }
    }
}
