//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHLY_HDDOANHTHU
    {
        public int THANHLY_DOANHTHU_ID { get; set; }
        public Nullable<int> HOPDONG_DOANHTHU_ID { get; set; }
        public Nullable<decimal> SOBIENBAN_TL { get; set; }
        public Nullable<System.DateTime> NGAYLAP_BBTL { get; set; }
        public string NGUOILAP_BBTL { get; set; }
        public string NOIDUNG_TL { get; set; }
        public Nullable<System.DateTime> NGAY_HIEULUC_TL { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HOPDONG_DOANHTHU HOPDONG_DOANHTHU { get; set; }
    }
}
