//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN_NHANCONG
    {
        public int ID_TT { get; set; }
        public Nullable<int> HOPDONG_NHANCONG_ID { get; set; }
        public Nullable<System.DateTime> TUNGAY_TT { get; set; }
        public Nullable<System.DateTime> DENNGAY_TT { get; set; }
        public Nullable<System.DateTime> NGAY_TT { get; set; }
        public Nullable<decimal> SOTIEN_TT { get; set; }
        public string SOUYNHIEMCHI_TT { get; set; }
        public string CHUTK_TT { get; set; }
        public string SOTK_TT { get; set; }
        public string NGANHANG_TT { get; set; }
        public string GHICHU_TT { get; set; }
        public string USER { get; set; }
    
        public virtual HOPDONG_NHANCONG HOPDONG_NHANCONG { get; set; }
    }
}
