//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANG_SD_CHIPHI
    {
        public int TINHTRANG_ID { get; set; }
        public Nullable<int> HOPDONG_CHIPHI_ID { get; set; }
        public string TEN_TB { get; set; }
        public string TINHTRANG_SD { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HOPDONG_CHIPHI HOPDONG_CHIPHI { get; set; }
    }
}
