//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENTHUE_TAM
    {
        public int BENTHUE_TAM_ID { get; set; }
        public string TEN { get; set; }
        public string DAIDIEN { get; set; }
        public string CHUCVU { get; set; }
        public string DIACHI { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NGAYCAP_CMND { get; set; }
        public string NOICAP_CMND { get; set; }
        public string MS_THUE { get; set; }
        public string DIENTHOAI { get; set; }
        public string TAIKHOAN { get; set; }
        public string NGANHANG { get; set; }
        public string FAX { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string TRINHDO { get; set; }
        public string CONGVIEC { get; set; }
    }
}
